services:
  pgsql:
    container_name: 'technical-interview-balast-postgres'
    image: 'postgres:16'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: 'technical-interview-balast'
      POSTGRES_DB: 'technical-interview-balast'
      POSTGRES_USER: 'technical-interview-balast'
      POSTGRES_PASSWORD: 'technical-interview-balast'
    volumes:
      - 'technical-interview-balast-pgsql:/var/lib/postgresql/data'
    networks:
      - backend
  app:
    container_name: 'technical-interview-balast-app'
    build: .
    ports:
      - '3000:3000' # assuming your app runs on port 3000
    environment:
      TYPEORM_HOST: pgsql
      TYPEORM_PORT: 5432
      TYPEORM_DATABASE: technical-interview-balast
      TYPEORM_USERNAME: technical-interview-balast
      TYPEORM_PASSWORD: technical-interview-balast
      NODE_ENV: production
    depends_on:
      - pgsql
    networks:
      - backend

networks:
  backend:
    driver: bridge
    name: shared-backend

volumes:
  technical-interview-balast-pgsql:
    driver: local
